begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(15);

select ok(not has_function_privilege('anon','public.claim_narrative_work(text,text,boolean)','execute'), 'client cannot reserve provider work');
select ok(not has_function_privilege('authenticated','public.finish_narrative_work(text,text,uuid,text,jsonb)','execute'), 'client cannot apply a judgment');
select * from public.create_room_with_host('STORY234','Host','story-host');
select * from public.join_game('STORY234','Guest','story-guest');
select * from public.start_game('STORY234','story-host');
create temporary table work as select public.claim_narrative_work('STORY234','story-host',false) as value;
select ok((select value->>'kind' from work)='generate','generation work reserved');
select is(public.claim_narrative_work('STORY234','story-guest',false),null::jsonb,'second worker cannot reserve concurrently');
select ok(public.finish_narrative_work('STORY234','story-host',(select (value->>'token')::uuid from work),'generate','{"situation":"Uma porta","updatedStorySummary":"Resumo","wordLimit":5}'::jsonb),'generation applied');
select ok(not public.finish_narrative_work('STORY234','story-host',(select (value->>'token')::uuid from work),'generate','{}'::jsonb),'completed lease cannot overwrite round');
update public.rounds set situation_ready_at=clock_timestamp()-interval '1 second' where game_id=(select id from public.games where code='STORY234');
select public.tick_round('STORY234','story-host');
select public.submit_round_answer('STORY234','story-host',(select id from public.rounds where game_id=(select id from public.games where code='STORY234')),'Abro a porta.');
select public.submit_round_answer('STORY234','story-guest',(select id from public.rounds where game_id=(select id from public.games where code='STORY234')),'Fecho a porta.');
truncate work;
insert into work select public.claim_narrative_work('STORY234','story-host',false);
select throws_ok($$select public.finish_narrative_work('STORY234','story-host',(select (value->>'token')::uuid from work),'judge','{"winnerPlayerId":"00000000-0000-0000-0000-000000000001","reason":"Motivo","continuation":"Continuação","nextSituation":"Próxima","updatedStorySummary":"Resumo"}'::jsonb)$$,'23514',null,'unknown winner rejected before scoring');
select public.fail_narrative_work('STORY234','story-host',(select (value->>'token')::uuid from work),'judge');
select is((select status::text from public.games where code='STORY234'),'judging_error','failed judgment preserves recoverable phase');
select is((select count(*) from public.answers where game_id=(select id from public.games where code='STORY234')),2::bigint,'failure preserves both private answers');
select is(public.claim_narrative_work('STORY234','story-host',false),null::jsonb,'reads do not endlessly retry failed provider');
select is(public.claim_narrative_work('STORY234','story-host',true),null::jsonb,'manual retry respects cooldown');
update public.games set work_until=clock_timestamp()-interval '1 second' where code='STORY234';
truncate work;
insert into work select public.claim_narrative_work('STORY234','story-host',true);
select ok(public.finish_narrative_work('STORY234','story-host',(select (value->>'token')::uuid from work),'judge',jsonb_build_object('winnerPlayerId',(select id from public.players where reconnect_token_hash='story-host'),'reason','Motivo','continuation','Continuação','nextSituation','Próxima','updatedStorySummary','Resumo')),'valid retry publishes result');
select ok(not public.finish_narrative_work('STORY234','story-host',(select (value->>'token')::uuid from work),'judge','{}'::jsonb),'duplicate result has no effect');
select is((select score::integer from public.players where reconnect_token_hash='story-host'),1,'one score for repeated judgment');
select ok((public.get_room_snapshot('STORY234','story-host')#>>'{state,control,revision}')::integer>0,'snapshot includes monotonic revision');
select * from finish();
rollback;
