begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(14);
select ok(not has_function_privilege('anon','public.heartbeat_room(text,text)','execute'),'presence is server-only');
select * from public.create_room_with_host('PAUSE234','Host','pause-host');
select * from public.join_game('PAUSE234','Guest','pause-guest');
select * from public.start_game('PAUSE234','pause-host');
select public.open_round('PAUSE234','pause-host','Uma porta','Resumo',5);
update public.rounds set situation_ready_at=clock_timestamp()-interval '1 second' where game_id=(select id from public.games where code='PAUSE234');
select public.tick_round('PAUSE234','pause-host');
select public.submit_round_answer('PAUSE234','pause-host',(select id from public.rounds where game_id=(select id from public.games where code='PAUSE234')),'Abro a porta.');
select public.update_player_presence('PAUSE234','pause-guest',false);
select is((select status::text from public.games where code='PAUSE234'),'paused','disconnect pauses instead of defeat');
select is((select paused_from::text from public.games where code='PAUSE234'),'answering','phase retained');
create temporary table frozen as select paused_answer_remaining_ms as value from public.games where code='PAUSE234';
select ok((select value between 0 and 10000 from frozen),'server retains only original remaining time');
select public.tick_round('PAUSE234','pause-host');
select is((select paused_answer_remaining_ms from public.games where code='PAUSE234'),(select value from frozen),'repeated reads do not change frozen time');
select is((select score::integer from public.players where reconnect_token_hash='pause-host'),0,'disconnect does not award points');
select is((public.get_room_snapshot('PAUSE234','pause-host')#>>'{state,answers,0,text}'),'Abro a porta.','confirmed answer survives pause');
select public.update_player_presence('PAUSE234','pause-guest',true);
select is((select status::text from public.games where code='PAUSE234'),'answering','reconnection restores server-confirmed phase');
select ok((select abs(extract(epoch from (answer_deadline_at-clock_timestamp()))*1000-(select value from frozen))<100 from public.rounds where game_id=(select id from public.games where code='PAUSE234')),'new deadline derives from server frozen time');
create temporary table before_heartbeat as select revision from public.games where code='PAUSE234';
select public.heartbeat_room('PAUSE234','pause-guest');
select is((select revision from public.games where code='PAUSE234'),(select revision from before_heartbeat),'heartbeat alone does not spam public revisions');
select public.submit_round_answer('PAUSE234','pause-guest',(select id from public.rounds where game_id=(select id from public.games where code='PAUSE234')),'Fecho a porta.');
create temporary table lease as select public.claim_narrative_work('PAUSE234','pause-host',false) as value;
select public.update_player_presence('PAUSE234','pause-guest',false);
select ok(public.finish_narrative_work('PAUSE234','pause-host',(select (value->>'token')::uuid from lease),'judge',jsonb_build_object('winnerPlayerId',(select id from public.players where reconnect_token_hash='pause-host'),'reason','Motivo','continuation','Continuação','nextSituation','Próxima','updatedStorySummary','Resumo')),'in-flight judgment applies atomically during pause');
select is((select status::text from public.games where code='PAUSE234'),'paused','worker does not unpause clients');
select is((select paused_from::text from public.games where code='PAUSE234'),'reveal','pause retains newly confirmed result phase');
select ok(not public.finish_narrative_work('PAUSE234','pause-host',(select (value->>'token')::uuid from lease),'judge','{}'::jsonb),'repeated paused result cannot duplicate score');
select * from finish();
rollback;
